/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.Vec3
import org.example.Color

fun main() {
    // Image
    val imageWidth: Int = 256
    val imageHeight: Int = 256

    // Render
    print("P3\n${imageWidth} ${imageHeight}\n255\n") 

    for  (j in 0..(imageHeight - 1)) {
        for  (i in 0..(imageWidth - 1)) {
            System.err.println("\rScanlines remaining: ${imageHeight - j} ")
            System.err.flush()

            val pixelColor = Color(
                i.toDouble() / (imageWidth - 1),
                j.toDouble() / (imageHeight - 1),
                0.0,
            )
            writeColor(pixelColor)

        }
    }
}

